import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

// Providers
import { ThemeProvider } from '@/components/context/theme';

// Styles
import { sans, mono } from '@/styles/fonts';
import '@/styles/globals.css';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children
}: Readonly<PropsWithChildren>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    [sans.variable, mono.variable, 'antialiased font-sans'],
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
